services:
  mysql:
    image: mysql:latest
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Qwerty
      - MYSQL_DATABASE=hello_world
      - MYSQL_USER=benchmarkdbuser
      - MYSQL_PASSWORD=benchmarkdbpass
#    volumes:
#      - C://storage/mysql:/var/lib/mysql:ro
    networks:
      - appnet

#volumes:
#  mysql-data-external:
#    driver: local

networks:
  appnet:
